/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActivityLog {
  'id' : bigint,
  'action' : string,
  'userId' : Principal,
  'role' : UserRole,
  'timestamp' : Time,
  'details' : string,
}
export interface Case {
  'id' : bigint,
  'status' : CaseStatus,
  'title' : string,
  'clientId' : Principal,
  'createdAt' : Time,
  'description' : string,
  'updatedAt' : Time,
  'priority' : Priority,
  'investigatorId' : [] | [Principal],
}
export interface CaseNote {
  'id' : bigint,
  'content' : string,
  'authorId' : Principal,
  'timestamp' : Time,
  'caseId' : bigint,
}
export type CaseStatus = { 'closed' : null } |
  { 'active' : null } |
  { 'pending' : null };
export interface Client {
  'id' : Principal,
  'name' : string,
  'email' : string,
  'kycStatus' : KYCStatus,
  'address' : string,
  'phone' : string,
}
export type ExternalBlob = Uint8Array;
export interface Inquiry {
  'id' : string,
  'status' : InquiryStatus,
  'serviceType' : string,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
  'phone' : string,
}
export type InquiryStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null } |
  { 'contacted' : null };
export type KYCStatus = { 'verified' : null } |
  { 'pending' : null } |
  { 'rejected' : null };
export interface Media {
  'id' : string,
  'blob' : [] | [ExternalBlob],
  'fileName' : string,
  'fileType' : string,
  'category' : string,
  'caseId' : [] | [bigint],
  'uploadedAt' : Time,
  'uploadedBy' : Principal,
}
export interface Message {
  'id' : bigint,
  'content' : string,
  'role' : UserRole,
  'timestamp' : Time,
  'caseId' : bigint,
  'senderId' : Principal,
}
export type Priority = { 'low' : null } |
  { 'high' : null } |
  { 'urgent' : null } |
  { 'medium' : null };
export interface Setting { 'key' : string, 'value' : string }
export interface Staff {
  'id' : Principal,
  'name' : string,
  'role' : StaffRole,
  'email' : string,
  'phone' : string,
  'lastActive' : Time,
}
export type StaffRole = { 'admin' : null } |
  { 'investigator' : null } |
  { 'analyst' : null };
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'role' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCaseNote' : ActorMethod<[bigint, string], undefined>,
  'addMedia' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      Principal,
      [] | [bigint],
      [] | [ExternalBlob],
    ],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignInvestigator' : ActorMethod<[bigint, Principal], undefined>,
  'createCase' : ActorMethod<[string, string, Principal, Priority], bigint>,
  'createClient' : ActorMethod<[string, string, string, string], undefined>,
  'createInquiry' : ActorMethod<
    [string, string, string, string, string],
    string
  >,
  'createStaff' : ActorMethod<[string, string, string, StaffRole], undefined>,
  'deleteMedia' : ActorMethod<[string], undefined>,
  'getAllCases' : ActorMethod<[], Array<Case>>,
  'getAllClients' : ActorMethod<[], Array<Client>>,
  'getAllInquiries' : ActorMethod<[], Array<Inquiry>>,
  'getAllMedia' : ActorMethod<[], Array<Media>>,
  'getAllMessagesForCase' : ActorMethod<[bigint, Principal], Array<Message>>,
  'getAllStaff' : ActorMethod<[], Array<Staff>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCaseById' : ActorMethod<[bigint], [] | [Case]>,
  'getCaseNotes' : ActorMethod<[bigint], Array<CaseNote>>,
  'getCasesByClient' : ActorMethod<[Principal], Array<Case>>,
  'getCasesByInvestigator' : ActorMethod<[Principal], Array<Case>>,
  'getClientById' : ActorMethod<[Principal], [] | [Client]>,
  'getClientCases' : ActorMethod<[Principal], Array<Case>>,
  'getLogsByUser' : ActorMethod<[Principal], Array<ActivityLog>>,
  'getMediaByCase' : ActorMethod<[bigint], Array<Media>>,
  'getMessagesForCase' : ActorMethod<[bigint], Array<Message>>,
  'getRecentLogs' : ActorMethod<[bigint], Array<ActivityLog>>,
  'getSettingByKey' : ActorMethod<[string], [] | [Setting]>,
  'getStaffById' : ActorMethod<[Principal], [] | [Staff]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[Principal, UserRole, string, bigint], undefined>,
  'updateCaseStatus' : ActorMethod<[bigint, CaseStatus], undefined>,
  'updateClient' : ActorMethod<
    [Principal, string, string, string, string, KYCStatus],
    undefined
  >,
  'updateInquiryStatus' : ActorMethod<[string, InquiryStatus], undefined>,
  'updateSetting' : ActorMethod<[string, string], undefined>,
  'updateStaff' : ActorMethod<
    [Principal, string, string, string, StaffRole],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];