/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Priority = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'urgent' : IDL.Null,
  'medium' : IDL.Null,
});
export const StaffRole = IDL.Variant({
  'admin' : IDL.Null,
  'investigator' : IDL.Null,
  'analyst' : IDL.Null,
});
export const CaseStatus = IDL.Variant({
  'closed' : IDL.Null,
  'active' : IDL.Null,
  'pending' : IDL.Null,
});
export const Time = IDL.Int;
export const Case = IDL.Record({
  'id' : IDL.Nat,
  'status' : CaseStatus,
  'title' : IDL.Text,
  'clientId' : IDL.Principal,
  'createdAt' : Time,
  'description' : IDL.Text,
  'updatedAt' : Time,
  'priority' : Priority,
  'investigatorId' : IDL.Opt(IDL.Principal),
});
export const KYCStatus = IDL.Variant({
  'verified' : IDL.Null,
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Client = IDL.Record({
  'id' : IDL.Principal,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'kycStatus' : KYCStatus,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const InquiryStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
  'contacted' : IDL.Null,
});
export const Inquiry = IDL.Record({
  'id' : IDL.Text,
  'status' : InquiryStatus,
  'serviceType' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
});
export const Media = IDL.Record({
  'id' : IDL.Text,
  'blob' : IDL.Opt(ExternalBlob),
  'fileName' : IDL.Text,
  'fileType' : IDL.Text,
  'category' : IDL.Text,
  'caseId' : IDL.Opt(IDL.Nat),
  'uploadedAt' : Time,
  'uploadedBy' : IDL.Principal,
});
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'role' : UserRole,
  'timestamp' : Time,
  'caseId' : IDL.Nat,
  'senderId' : IDL.Principal,
});
export const Staff = IDL.Record({
  'id' : IDL.Principal,
  'name' : IDL.Text,
  'role' : StaffRole,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'lastActive' : Time,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const CaseNote = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'authorId' : IDL.Principal,
  'timestamp' : Time,
  'caseId' : IDL.Nat,
});
export const ActivityLog = IDL.Record({
  'id' : IDL.Nat,
  'action' : IDL.Text,
  'userId' : IDL.Principal,
  'role' : UserRole,
  'timestamp' : Time,
  'details' : IDL.Text,
});
export const Setting = IDL.Record({ 'key' : IDL.Text, 'value' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCaseNote' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'addMedia' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Principal,
        IDL.Opt(IDL.Nat),
        IDL.Opt(ExternalBlob),
      ],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignInvestigator' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
  'createCase' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Principal, Priority],
      [IDL.Nat],
      [],
    ),
  'createClient' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'createInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createStaff' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, StaffRole], [], []),
  'deleteMedia' : IDL.Func([IDL.Text], [], []),
  'getAllCases' : IDL.Func([], [IDL.Vec(Case)], ['query']),
  'getAllClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
  'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getAllMedia' : IDL.Func([], [IDL.Vec(Media)], ['query']),
  'getAllMessagesForCase' : IDL.Func(
      [IDL.Nat, IDL.Principal],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getAllStaff' : IDL.Func([], [IDL.Vec(Staff)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCaseById' : IDL.Func([IDL.Nat], [IDL.Opt(Case)], ['query']),
  'getCaseNotes' : IDL.Func([IDL.Nat], [IDL.Vec(CaseNote)], ['query']),
  'getCasesByClient' : IDL.Func([IDL.Principal], [IDL.Vec(Case)], ['query']),
  'getCasesByInvestigator' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Case)],
      ['query'],
    ),
  'getClientById' : IDL.Func([IDL.Principal], [IDL.Opt(Client)], ['query']),
  'getClientCases' : IDL.Func([IDL.Principal], [IDL.Vec(Case)], ['query']),
  'getLogsByUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ActivityLog)],
      ['query'],
    ),
  'getMediaByCase' : IDL.Func([IDL.Nat], [IDL.Vec(Media)], ['query']),
  'getMessagesForCase' : IDL.Func([IDL.Nat], [IDL.Vec(Message)], ['query']),
  'getRecentLogs' : IDL.Func([IDL.Nat], [IDL.Vec(ActivityLog)], ['query']),
  'getSettingByKey' : IDL.Func([IDL.Text], [IDL.Opt(Setting)], ['query']),
  'getStaffById' : IDL.Func([IDL.Principal], [IDL.Opt(Staff)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func(
      [IDL.Principal, UserRole, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'updateCaseStatus' : IDL.Func([IDL.Nat, CaseStatus], [], []),
  'updateClient' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Text, IDL.Text, IDL.Text, KYCStatus],
      [],
      [],
    ),
  'updateInquiryStatus' : IDL.Func([IDL.Text, InquiryStatus], [], []),
  'updateSetting' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateStaff' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Text, IDL.Text, StaffRole],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Priority = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'urgent' : IDL.Null,
    'medium' : IDL.Null,
  });
  const StaffRole = IDL.Variant({
    'admin' : IDL.Null,
    'investigator' : IDL.Null,
    'analyst' : IDL.Null,
  });
  const CaseStatus = IDL.Variant({
    'closed' : IDL.Null,
    'active' : IDL.Null,
    'pending' : IDL.Null,
  });
  const Time = IDL.Int;
  const Case = IDL.Record({
    'id' : IDL.Nat,
    'status' : CaseStatus,
    'title' : IDL.Text,
    'clientId' : IDL.Principal,
    'createdAt' : Time,
    'description' : IDL.Text,
    'updatedAt' : Time,
    'priority' : Priority,
    'investigatorId' : IDL.Opt(IDL.Principal),
  });
  const KYCStatus = IDL.Variant({
    'verified' : IDL.Null,
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Client = IDL.Record({
    'id' : IDL.Principal,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'kycStatus' : KYCStatus,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const InquiryStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
    'contacted' : IDL.Null,
  });
  const Inquiry = IDL.Record({
    'id' : IDL.Text,
    'status' : InquiryStatus,
    'serviceType' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
  });
  const Media = IDL.Record({
    'id' : IDL.Text,
    'blob' : IDL.Opt(ExternalBlob),
    'fileName' : IDL.Text,
    'fileType' : IDL.Text,
    'category' : IDL.Text,
    'caseId' : IDL.Opt(IDL.Nat),
    'uploadedAt' : Time,
    'uploadedBy' : IDL.Principal,
  });
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'role' : UserRole,
    'timestamp' : Time,
    'caseId' : IDL.Nat,
    'senderId' : IDL.Principal,
  });
  const Staff = IDL.Record({
    'id' : IDL.Principal,
    'name' : IDL.Text,
    'role' : StaffRole,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'lastActive' : Time,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const CaseNote = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'authorId' : IDL.Principal,
    'timestamp' : Time,
    'caseId' : IDL.Nat,
  });
  const ActivityLog = IDL.Record({
    'id' : IDL.Nat,
    'action' : IDL.Text,
    'userId' : IDL.Principal,
    'role' : UserRole,
    'timestamp' : Time,
    'details' : IDL.Text,
  });
  const Setting = IDL.Record({ 'key' : IDL.Text, 'value' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCaseNote' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'addMedia' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Principal,
          IDL.Opt(IDL.Nat),
          IDL.Opt(ExternalBlob),
        ],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignInvestigator' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
    'createCase' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Principal, Priority],
        [IDL.Nat],
        [],
      ),
    'createClient' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'createInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createStaff' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, StaffRole], [], []),
    'deleteMedia' : IDL.Func([IDL.Text], [], []),
    'getAllCases' : IDL.Func([], [IDL.Vec(Case)], ['query']),
    'getAllClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
    'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getAllMedia' : IDL.Func([], [IDL.Vec(Media)], ['query']),
    'getAllMessagesForCase' : IDL.Func(
        [IDL.Nat, IDL.Principal],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getAllStaff' : IDL.Func([], [IDL.Vec(Staff)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCaseById' : IDL.Func([IDL.Nat], [IDL.Opt(Case)], ['query']),
    'getCaseNotes' : IDL.Func([IDL.Nat], [IDL.Vec(CaseNote)], ['query']),
    'getCasesByClient' : IDL.Func([IDL.Principal], [IDL.Vec(Case)], ['query']),
    'getCasesByInvestigator' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Case)],
        ['query'],
      ),
    'getClientById' : IDL.Func([IDL.Principal], [IDL.Opt(Client)], ['query']),
    'getClientCases' : IDL.Func([IDL.Principal], [IDL.Vec(Case)], ['query']),
    'getLogsByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ActivityLog)],
        ['query'],
      ),
    'getMediaByCase' : IDL.Func([IDL.Nat], [IDL.Vec(Media)], ['query']),
    'getMessagesForCase' : IDL.Func([IDL.Nat], [IDL.Vec(Message)], ['query']),
    'getRecentLogs' : IDL.Func([IDL.Nat], [IDL.Vec(ActivityLog)], ['query']),
    'getSettingByKey' : IDL.Func([IDL.Text], [IDL.Opt(Setting)], ['query']),
    'getStaffById' : IDL.Func([IDL.Principal], [IDL.Opt(Staff)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func(
        [IDL.Principal, UserRole, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'updateCaseStatus' : IDL.Func([IDL.Nat, CaseStatus], [], []),
    'updateClient' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text, IDL.Text, IDL.Text, KYCStatus],
        [],
        [],
      ),
    'updateInquiryStatus' : IDL.Func([IDL.Text, InquiryStatus], [], []),
    'updateSetting' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateStaff' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text, IDL.Text, StaffRole],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };