/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Client {
    id: Principal;
    name: string;
    email: string;
    kycStatus: KYCStatus;
    address: string;
    phone: string;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface CaseNote {
    id: bigint;
    content: string;
    authorId: Principal;
    timestamp: Time;
    caseId: bigint;
}
export interface Case {
    id: bigint;
    status: CaseStatus;
    title: string;
    clientId: Principal;
    createdAt: Time;
    description: string;
    updatedAt: Time;
    priority: Priority;
    investigatorId?: Principal;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface ActivityLog {
    id: bigint;
    action: string;
    userId: Principal;
    role: UserRole;
    timestamp: Time;
    details: string;
}
export interface Staff {
    id: Principal;
    name: string;
    role: StaffRole;
    email: string;
    phone: string;
    lastActive: Time;
}
export interface Message {
    id: bigint;
    content: string;
    role: UserRole;
    timestamp: Time;
    caseId: bigint;
    senderId: Principal;
}
export interface Setting {
    key: string;
    value: string;
}
export interface Inquiry {
    id: string;
    status: InquiryStatus;
    serviceType: string;
    name: string;
    email: string;
    message: string;
    timestamp: bigint;
    phone: string;
}
export interface Media {
    id: string;
    blob?: ExternalBlob;
    fileName: string;
    fileType: string;
    category: string;
    caseId?: bigint;
    uploadedAt: Time;
    uploadedBy: Principal;
}
export interface UserProfile {
    name: string;
    role: string;
    email: string;
    phone: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum CaseStatus {
    closed = "closed",
    active = "active",
    pending = "pending"
}
export enum InquiryStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected",
    contacted = "contacted"
}
export enum KYCStatus {
    verified = "verified",
    pending = "pending",
    rejected = "rejected"
}
export enum Priority {
    low = "low",
    high = "high",
    urgent = "urgent",
    medium = "medium"
}
export enum StaffRole {
    admin = "admin",
    investigator = "investigator",
    analyst = "analyst"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCaseNote(caseId: bigint, content: string): Promise<void>;
    addMedia(id: string, fileName: string, fileType: string, category: string, uploadedBy: Principal, caseId: bigint | null, blob: ExternalBlob | null): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignInvestigator(caseId: bigint, investigatorId: Principal): Promise<void>;
    createCase(title: string, description: string, clientId: Principal, priority: Priority): Promise<bigint>;
    createClient(name: string, phone: string, email: string, address: string): Promise<void>;
    createInquiry(name: string, phone: string, email: string, message: string, serviceType: string): Promise<string>;
    createStaff(name: string, email: string, phone: string, role: StaffRole): Promise<void>;
    deleteMedia(id: string): Promise<void>;
    getAllCases(): Promise<Array<Case>>;
    getAllClients(): Promise<Array<Client>>;
    getAllInquiries(): Promise<Array<Inquiry>>;
    getAllMedia(): Promise<Array<Media>>;
    getAllMessagesForCase(caseId: bigint, requesterId: Principal): Promise<Array<Message>>;
    getAllStaff(): Promise<Array<Staff>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCaseById(caseId: bigint): Promise<Case | null>;
    getCaseNotes(caseId: bigint): Promise<Array<CaseNote>>;
    getCasesByClient(clientId: Principal): Promise<Array<Case>>;
    getCasesByInvestigator(investigatorId: Principal): Promise<Array<Case>>;
    getClientById(clientId: Principal): Promise<Client | null>;
    getClientCases(clientId: Principal): Promise<Array<Case>>;
    getLogsByUser(userId: Principal): Promise<Array<ActivityLog>>;
    getMediaByCase(caseId: bigint): Promise<Array<Media>>;
    getMessagesForCase(caseId: bigint): Promise<Array<Message>>;
    getRecentLogs(limit: bigint): Promise<Array<ActivityLog>>;
    getSettingByKey(key: string): Promise<Setting | null>;
    getStaffById(staffId: Principal): Promise<Staff | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    sendMessage(senderId: Principal, role: UserRole, content: string, caseId: bigint): Promise<void>;
    updateCaseStatus(caseId: bigint, status: CaseStatus): Promise<void>;
    updateClient(id: Principal, name: string, phone: string, email: string, address: string, kycStatus: KYCStatus): Promise<void>;
    updateInquiryStatus(id: string, status: InquiryStatus): Promise<void>;
    updateSetting(key: string, value: string): Promise<void>;
    updateStaff(id: Principal, name: string, email: string, phone: string, role: StaffRole): Promise<void>;
}
import type { ActivityLog as _ActivityLog, Case as _Case, CaseStatus as _CaseStatus, Client as _Client, ExternalBlob as _ExternalBlob, Inquiry as _Inquiry, InquiryStatus as _InquiryStatus, KYCStatus as _KYCStatus, Media as _Media, Message as _Message, Priority as _Priority, Setting as _Setting, Staff as _Staff, StaffRole as _StaffRole, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCaseNote(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCaseNote(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCaseNote(arg0, arg1);
            return result;
        }
    }
    async addMedia(arg0: string, arg1: string, arg2: string, arg3: string, arg4: Principal, arg5: bigint | null, arg6: ExternalBlob | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMedia(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg5), await to_candid_opt_n9(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMedia(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg5), await to_candid_opt_n9(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignInvestigator(arg0: bigint, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignInvestigator(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignInvestigator(arg0, arg1);
            return result;
        }
    }
    async createCase(arg0: string, arg1: string, arg2: Principal, arg3: Priority): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createCase(arg0, arg1, arg2, to_candid_Priority_n13(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCase(arg0, arg1, arg2, to_candid_Priority_n13(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async createClient(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createClient(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createClient(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createInquiry(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createInquiry(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInquiry(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createStaff(arg0: string, arg1: string, arg2: string, arg3: StaffRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createStaff(arg0, arg1, arg2, to_candid_StaffRole_n15(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStaff(arg0, arg1, arg2, to_candid_StaffRole_n15(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async deleteMedia(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMedia(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMedia(arg0);
            return result;
        }
    }
    async getAllCases(): Promise<Array<Case>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCases();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCases();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllClients(): Promise<Array<Client>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllClients();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllClients();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllInquiries(): Promise<Array<Inquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInquiries();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInquiries();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMedia(): Promise<Array<Media>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMedia();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMedia();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMessagesForCase(arg0: bigint, arg1: Principal): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMessagesForCase(arg0, arg1);
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMessagesForCase(arg0, arg1);
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllStaff(): Promise<Array<Staff>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStaff();
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStaff();
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCaseById(arg0: bigint): Promise<Case | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCaseById(arg0);
                return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCaseById(arg0);
            return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCaseNotes(arg0: bigint): Promise<Array<CaseNote>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCaseNotes(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCaseNotes(arg0);
            return result;
        }
    }
    async getCasesByClient(arg0: Principal): Promise<Array<Case>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCasesByClient(arg0);
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCasesByClient(arg0);
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCasesByInvestigator(arg0: Principal): Promise<Array<Case>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCasesByInvestigator(arg0);
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCasesByInvestigator(arg0);
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClientById(arg0: Principal): Promise<Client | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getClientById(arg0);
                return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClientById(arg0);
            return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClientCases(arg0: Principal): Promise<Array<Case>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClientCases(arg0);
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClientCases(arg0);
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLogsByUser(arg0: Principal): Promise<Array<ActivityLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLogsByUser(arg0);
                return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLogsByUser(arg0);
            return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMediaByCase(arg0: bigint): Promise<Array<Media>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMediaByCase(arg0);
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMediaByCase(arg0);
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessagesForCase(arg0: bigint): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessagesForCase(arg0);
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessagesForCase(arg0);
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecentLogs(arg0: bigint): Promise<Array<ActivityLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecentLogs(arg0);
                return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecentLogs(arg0);
            return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSettingByKey(arg0: string): Promise<Setting | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSettingByKey(arg0);
                return from_candid_opt_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSettingByKey(arg0);
            return from_candid_opt_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStaffById(arg0: Principal): Promise<Staff | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStaffById(arg0);
                return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStaffById(arg0);
            return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async sendMessage(arg0: Principal, arg1: UserRole, arg2: string, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return result;
        }
    }
    async updateCaseStatus(arg0: bigint, arg1: CaseStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCaseStatus(arg0, to_candid_CaseStatus_n58(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCaseStatus(arg0, to_candid_CaseStatus_n58(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateClient(arg0: Principal, arg1: string, arg2: string, arg3: string, arg4: string, arg5: KYCStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateClient(arg0, arg1, arg2, arg3, arg4, to_candid_KYCStatus_n60(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateClient(arg0, arg1, arg2, arg3, arg4, to_candid_KYCStatus_n60(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async updateInquiryStatus(arg0: string, arg1: InquiryStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInquiryStatus(arg0, to_candid_InquiryStatus_n62(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInquiryStatus(arg0, to_candid_InquiryStatus_n62(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateSetting(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSetting(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSetting(arg0, arg1);
            return result;
        }
    }
    async updateStaff(arg0: Principal, arg1: string, arg2: string, arg3: string, arg4: StaffRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStaff(arg0, arg1, arg2, arg3, to_candid_StaffRole_n15(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStaff(arg0, arg1, arg2, arg3, to_candid_StaffRole_n15(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
}
function from_candid_ActivityLog_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActivityLog): ActivityLog {
    return from_candid_record_n55(_uploadFile, _downloadFile, value);
}
function from_candid_CaseStatus_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaseStatus): CaseStatus {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Case_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Case): Case {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Client_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Client): Client {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_InquiryStatus_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InquiryStatus): InquiryStatus {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_Inquiry_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Inquiry): Inquiry {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_KYCStatus_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _KYCStatus): KYCStatus {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
async function from_candid_Media_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Media): Promise<Media> {
    return await from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_Message_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Message): Message {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_Priority_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Priority): Priority {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_StaffRole_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StaffRole): StaffRole {
    return from_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function from_candid_Staff_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Staff): Staff {
    return from_candid_record_n47(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n39(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Case]): Case | null {
    return value.length === 0 ? null : from_candid_Case_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Client]): Client | null {
    return value.length === 0 ? null : from_candid_Client_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Setting]): Setting | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Staff]): Staff | null {
    return value.length === 0 ? null : from_candid_Staff_n46(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _CaseStatus;
    title: string;
    clientId: Principal;
    createdAt: _Time;
    description: string;
    updatedAt: _Time;
    priority: _Priority;
    investigatorId: [] | [Principal];
}): {
    id: bigint;
    status: CaseStatus;
    title: string;
    clientId: Principal;
    createdAt: Time;
    description: string;
    updatedAt: Time;
    priority: Priority;
    investigatorId?: Principal;
} {
    return {
        id: value.id,
        status: from_candid_CaseStatus_n20(_uploadFile, _downloadFile, value.status),
        title: value.title,
        clientId: value.clientId,
        createdAt: value.createdAt,
        description: value.description,
        updatedAt: value.updatedAt,
        priority: from_candid_Priority_n22(_uploadFile, _downloadFile, value.priority),
        investigatorId: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.investigatorId))
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    name: string;
    email: string;
    kycStatus: _KYCStatus;
    address: string;
    phone: string;
}): {
    id: Principal;
    name: string;
    email: string;
    kycStatus: KYCStatus;
    address: string;
    phone: string;
} {
    return {
        id: value.id,
        name: value.name,
        email: value.email,
        kycStatus: from_candid_KYCStatus_n28(_uploadFile, _downloadFile, value.kycStatus),
        address: value.address,
        phone: value.phone
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _InquiryStatus;
    serviceType: string;
    name: string;
    email: string;
    message: string;
    timestamp: bigint;
    phone: string;
}): {
    id: string;
    status: InquiryStatus;
    serviceType: string;
    name: string;
    email: string;
    message: string;
    timestamp: bigint;
    phone: string;
} {
    return {
        id: value.id,
        status: from_candid_InquiryStatus_n33(_uploadFile, _downloadFile, value.status),
        serviceType: value.serviceType,
        name: value.name,
        email: value.email,
        message: value.message,
        timestamp: value.timestamp,
        phone: value.phone
    };
}
async function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    blob: [] | [_ExternalBlob];
    fileName: string;
    fileType: string;
    category: string;
    caseId: [] | [bigint];
    uploadedAt: _Time;
    uploadedBy: Principal;
}): Promise<{
    id: string;
    blob?: ExternalBlob;
    fileName: string;
    fileType: string;
    category: string;
    caseId?: bigint;
    uploadedAt: Time;
    uploadedBy: Principal;
}> {
    return {
        id: value.id,
        blob: record_opt_to_undefined(await from_candid_opt_n38(_uploadFile, _downloadFile, value.blob)),
        fileName: value.fileName,
        fileType: value.fileType,
        category: value.category,
        caseId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.caseId)),
        uploadedAt: value.uploadedAt,
        uploadedBy: value.uploadedBy
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    content: string;
    role: _UserRole;
    timestamp: _Time;
    caseId: bigint;
    senderId: Principal;
}): {
    id: bigint;
    content: string;
    role: UserRole;
    timestamp: Time;
    caseId: bigint;
    senderId: Principal;
} {
    return {
        id: value.id,
        content: value.content,
        role: from_candid_UserRole_n43(_uploadFile, _downloadFile, value.role),
        timestamp: value.timestamp,
        caseId: value.caseId,
        senderId: value.senderId
    };
}
function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    name: string;
    role: _StaffRole;
    email: string;
    phone: string;
    lastActive: _Time;
}): {
    id: Principal;
    name: string;
    role: StaffRole;
    email: string;
    phone: string;
    lastActive: Time;
} {
    return {
        id: value.id,
        name: value.name,
        role: from_candid_StaffRole_n48(_uploadFile, _downloadFile, value.role),
        email: value.email,
        phone: value.phone,
        lastActive: value.lastActive
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    action: string;
    userId: Principal;
    role: _UserRole;
    timestamp: _Time;
    details: string;
}): {
    id: bigint;
    action: string;
    userId: Principal;
    role: UserRole;
    timestamp: Time;
    details: string;
} {
    return {
        id: value.id,
        action: value.action,
        userId: value.userId,
        role: from_candid_UserRole_n43(_uploadFile, _downloadFile, value.role),
        timestamp: value.timestamp,
        details: value.details
    };
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    closed: null;
} | {
    active: null;
} | {
    pending: null;
}): CaseStatus {
    return "closed" in value ? CaseStatus.closed : "active" in value ? CaseStatus.active : "pending" in value ? CaseStatus.pending : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    urgent: null;
} | {
    medium: null;
}): Priority {
    return "low" in value ? Priority.low : "high" in value ? Priority.high : "urgent" in value ? Priority.urgent : "medium" in value ? Priority.medium : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    verified: null;
} | {
    pending: null;
} | {
    rejected: null;
}): KYCStatus {
    return "verified" in value ? KYCStatus.verified : "pending" in value ? KYCStatus.pending : "rejected" in value ? KYCStatus.rejected : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} | {
    contacted: null;
}): InquiryStatus {
    return "pending" in value ? InquiryStatus.pending : "approved" in value ? InquiryStatus.approved : "rejected" in value ? InquiryStatus.rejected : "contacted" in value ? InquiryStatus.contacted : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    investigator: null;
} | {
    analyst: null;
}): StaffRole {
    return "admin" in value ? StaffRole.admin : "investigator" in value ? StaffRole.investigator : "analyst" in value ? StaffRole.analyst : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Case>): Array<Case> {
    return value.map((x)=>from_candid_Case_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Client>): Array<Client> {
    return value.map((x)=>from_candid_Client_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Inquiry>): Array<Inquiry> {
    return value.map((x)=>from_candid_Inquiry_n31(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Media>): Promise<Array<Media>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Media_n36(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Message>): Array<Message> {
    return value.map((x)=>from_candid_Message_n41(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Staff>): Array<Staff> {
    return value.map((x)=>from_candid_Staff_n46(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ActivityLog>): Array<ActivityLog> {
    return value.map((x)=>from_candid_ActivityLog_n54(_uploadFile, _downloadFile, x));
}
function to_candid_CaseStatus_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CaseStatus): _CaseStatus {
    return to_candid_variant_n59(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_InquiryStatus_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InquiryStatus): _InquiryStatus {
    return to_candid_variant_n63(_uploadFile, _downloadFile, value);
}
function to_candid_KYCStatus_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: KYCStatus): _KYCStatus {
    return to_candid_variant_n61(_uploadFile, _downloadFile, value);
}
function to_candid_Priority_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Priority): _Priority {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_StaffRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StaffRole): _StaffRole {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
async function to_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Priority): {
    low: null;
} | {
    high: null;
} | {
    urgent: null;
} | {
    medium: null;
} {
    return value == Priority.low ? {
        low: null
    } : value == Priority.high ? {
        high: null
    } : value == Priority.urgent ? {
        urgent: null
    } : value == Priority.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StaffRole): {
    admin: null;
} | {
    investigator: null;
} | {
    analyst: null;
} {
    return value == StaffRole.admin ? {
        admin: null
    } : value == StaffRole.investigator ? {
        investigator: null
    } : value == StaffRole.analyst ? {
        analyst: null
    } : value;
}
function to_candid_variant_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CaseStatus): {
    closed: null;
} | {
    active: null;
} | {
    pending: null;
} {
    return value == CaseStatus.closed ? {
        closed: null
    } : value == CaseStatus.active ? {
        active: null
    } : value == CaseStatus.pending ? {
        pending: null
    } : value;
}
function to_candid_variant_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: KYCStatus): {
    verified: null;
} | {
    pending: null;
} | {
    rejected: null;
} {
    return value == KYCStatus.verified ? {
        verified: null
    } : value == KYCStatus.pending ? {
        pending: null
    } : value == KYCStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InquiryStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} | {
    contacted: null;
} {
    return value == InquiryStatus.pending ? {
        pending: null
    } : value == InquiryStatus.approved ? {
        approved: null
    } : value == InquiryStatus.rejected ? {
        rejected: null
    } : value == InquiryStatus.contacted ? {
        contacted: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
